FROM ghcr.io/graalvm/native-image-community:21 AS builder
WORKDIR /app
COPY . .
RUN ./gradlew nativeCompile --no-daemon

FROM ubuntu:24.04
WORKDIR /app
COPY --from=builder /app/build/native/nativeCompile/shoptracker .
RUN groupadd -r appuser && useradd -r -g appuser appuser
USER appuser
EXPOSE 8080
ENTRYPOINT ["./shoptracker"]
